name: CICDNwsInventaire

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code 🔄
        uses: actions/checkout@v3

      - name: Setup .NET 6 🛠
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      
      - name: Restore Dependencies 🛠
        run: dotnet restore

      - name: Build App 🚀
        run: dotnet publish -c Release --no-restore

      - run: ls -lah

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push to GitHub registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/hugo-marc-76/nwsinventaire:latest
          target: nwsinventaire